aesop/aesop-gel

- pipeline/AddToCartButton/AddToCartButton.module.css
- pipeline/SubNav/SubNav.module.css
- src/components/BodyCopy/BodyCopy.js
- src/components/BodyCopy/BodyCopy.module.css
- src/components/BodyCopy/BodyCopy.spec.js
- src/components/BodyCopy/BodyCopy.stories.js
- src/components/Button/Button.module.css
- src/components/Heading/Heading.module.css
- src/components/Hyperlink/Hyperlink.module.css
- src/components/ImageWithHeaderAndContent/ImageWithHeaderAndContent.module.css
- src/components/Paragraph/Paragraph.module.css
This PR introduces the BodyCopy Component. 
- Add BodyCopy component and styles
JIRA: https://aesoponline.atlassian.net/browse/AES-825
> [Feature][AES-825] BodyCopy Component

- src/components/BodyCopy/BodyCopy.stories.js
- src/components/BynderWidget/BynderWidget.js
- src/components/BynderWidget/BynderWidget.module.css
- src/components/BynderWidget/BynderWidget.spec.js
- src/components/BynderWidget/BynderWidget.stories.js
- src/components/BynderWidget/__snapshots__/BynderWidget.spec.js.snap
- src/components/BynderWidget/index.js
- src/customHooks/useScript.js
This PR Introduces the Bynder Component and UseScript Hook
Addresses https://aesoponline.atlassian.net/browse/AES-830
> [Feature][AES-830] Bynder Component and UseScript Hook

- src/components/Carousel/Carousel.fixture.js
- src/components/Carousel/Carousel.js
- src/components/Carousel/Carousel.stories.mdx
This PR adds the `id` prop to the Carousel Component, and updates storybook and fixtures.
> [Update] Carousel Component Props

- .gitignore
The PR is to add .idea/ to .gitignore
> [Update]: add .idea to .gitignore

- src/components/FlyinPanel/FlyinPanel.module.css
This PR makes CSS adjustments to the FlyinPanel Component to address https://aesoponline.atlassian.net/browse/AES-1283
> [Feature][AES-1283] CSS Adjustments to FlyinPanel Component

- src/utils/product/product.spec.js
This PR makes adjustments to the Add To Cart Button component and the PDP Header component to accommodate the new layout requirements and the custom url and label for the ATC Button.
https://aesoponline.atlassian.net/browse/AES-1284
> [Feature][AES-1284] Add To Cart Button

- src/components/ContentHubArticle/ContentHubArticle.js
- src/components/ContentHubArticle/ContentHubArticle.module.css
- src/components/ContentHubArticle/ContentHubArticle.stories.mdx
- src/components/ContentHubArticle/__snapshots__/ContentHubArticle.spec.js.snap
- src/components/ContentHubArticleList/ContentHubArticleList.js
- src/components/ContentHubArticleList/ContentHubArticleList.module.css
- src/components/ContentHubArticleList/__snapshots__/ContentHubArticleList.spec.js.snap
- src/components/ReadMore/ReadMore.js
- src/components/ReadMore/ReadMore.module.css
Update ReadMore and ContentHubList Component for responsive view
> feat: update responsive view for Readmore & ContenthubList

- src/components/MediaWithContent/MediaWithContent.fixture.js
- src/components/MediaWithContent/MediaWithContent.js
- src/components/MediaWithContent/MediaWithContent.stories.mdx
- src/components/MediaWithContent/components/Media/Media.js
This PR adds an option for a `foregroundImageLink`
https://aesoponline.atlassian.net/browse/AES-1507
> [Feature][AES-1507] Foreground image link

- package.json
- src/components/Carousel/__snapshots__/Carousel.spec.js.snap
- src/components/ImageCarousel/__snapshots__/ImageCarousel.spec.js.snap
This PR fixes the react slick version
> Update - Fix React Slick Version

- src/components/ContentHubArticle/__snapshots__/ContentHubArticle.spec.js.snap
- src/components/ContentHubArticleList/__snapshots__/ContentHubArticleList.spec.js.snap
- src/components/DialogBanner/__snapshots__/DialogBanner.spec.js.snap
- src/components/ImageCarousel/__snapshots__/ImageCarousel.spec.js.snap
- src/components/Overlay/__snapshots__/Overlay.spec.js.snap
- src/components/Podium/__snapshots__/Podium.spec.js.snap
- src/components/ReadMore/__snapshots__/ReadMore.spec.js.snap
- src/components/Transition/__snapshots__/Transition.spec.js.snap
- src/components/Video/__snapshots__/Video.spec.js.snap
> feat: temp update snapshots

- package-lock.json
- package.json
feat: update gel to version 1.4.0
> feat: update gel to version 1.4.0

- src/components/MediaWithContent/components/Content/Content.module.css
- src/components/MediaWithContent/components/Media/Media.module.css
**PR link**
https://aesoponline.atlassian.net/browse/AES-1499
**Description**
Fix IE 11 layout of 'Hero full width' with background video:
- text section
- video/image holder position
> [Feature/AES-1499-hero-fw-video]: IE layout

- src/components/Carousel/Carousel.module.css
- src/components/Carousel/components/CarouselIntroduction/CarouselIntroduction.module.css
- src/components/Carousel/components/Slide/Slide.js
- src/components/Carousel/components/Slide/Slide.module.css
- src/components/Hyperlink/Hyperlink.js
- src/components/Hyperlink/Hyperlink.module.css
- src/components/MediaWithContent/components/Content/Content.module.css
This PR address font sizing, spacing and text colour as requested in https://aesoponline.atlassian.net/browse/AES-1684
> [Feature][AES-1684] PDP font adjustments

- src/components/BodyCopy/__snapshots__/BodyCopy.spec.js.snap
- src/components/Carousel/__snapshots__/Carousel.spec.js.snap
- src/components/Carousel/components/Slide/__snapshots__/Slide.spec.js.snap
- src/components/StoreDetailHeader/__snapshots__/StoreDetailHeader.spec.js.snap
This PR updates the test specs related to AES-1684
> [Feature][AES-1684] Update tests spec

- src/components/Carousel/Carousel.module.css
- src/components/MediaWithContent/components/Content/Content.module.css
This PR address some comments and changes in https://aesoponline.atlassian.net/browse/AES-1684
> [Hotfix][AES-1684] UX feedback for font size

- src/components/DoubleMedia/__snapshots__/DoubleMedia.spec.js.snap
- src/components/DoubleMedia/components/MediaBlock/MediaBlock.js
- src/components/DoubleMedia/components/MediaBlock/MediaBlock.module.css
- The Header is updated to 16px Suisse Int’l Medium #333333
- The padding reflects the padding on the live example (https://www.aesop.com/au/r/page_00003RT1)
- Header will be underlined when hovering over either heading or image
> [Update][AES-1728]:Slice > Double Image styling

- src/components/Podium/Podium.js
Small PR to pass the `data-test-ref` value onto the `section` element if provided. 
This will help with @mishmaccas automation testing.
> Passing data-test-ref value to podiums section element

- src/components/Video/Video.stories.mdx
- src/components/Video/__snapshots__/Video.spec.js.snap
- src/components/Video/components/VideoPlayer/VideoPlayer.js
Addresses video source issue raised in https://aesoponline.atlassian.net/browse/AES-1734
> [Feature][AES-1734] Add responsive source logic to Video Component

- src/components/SecondaryMessage/SecondaryMessage.module.css
- src/components/SecondaryMessage/__snapshots__/SecondaryMessage.spec.js.snap
- src/components/SecondaryMessage/components/Message/Message.js
- src/components/SecondaryMessage/components/Message/Message.module.css
- src/components/SecondaryMessage/components/Message/__snapshots__/Message.spec.js.snap
https://aesoponline.atlassian.net/browse/AES-1647
update message border color to `#999`
add hover transition effects
See as below:
https://im.ezgif.com/tmp/ezgif-1-ec970b59c999.gif
> [Update][Feature/AES-1647]: update message border color & add hover effects

- src/components/SecondaryMessage/SecondaryMessage.module.css
Add background color to Secondary Message
> [Update][Feature/AES-1647] Add background color to Secondary Message

- src/components/SecondaryMessage/components/Message/Message.module.css
Update][feature/AES-1647] Secondary Message styles
> Update][feature/AES-1647] Secondary Message styles

- .storybook/main.js
- .storybook/preview.js
- src/components/LinkButtonGroup/LinkButtonGroup.module.css
- src/components/MediaWithContent/MediaWithContent.fixture.js
- src/components/MediaWithContent/MediaWithContent.js
- src/components/MediaWithContent/MediaWithContent.module.css
- src/components/MediaWithContent/MediaWithContent.stories.mdx
This PR addressed the offset issue in https://aesoponline.atlassian.net/browse/AES-1735
> [Feature][AES-1735] Hero Slice offset

- src/components/MediaWithContent/MediaWithContent.js
- src/components/MediaWithContent/MediaWithContent.stories.mdx
- src/components/MediaWithContent/components/Content/Content.js
- src/components/MediaWithContent/components/Content/Content.module.css
This PR adds topOffest to content within Hero Slices
> [Feature][AES-1735] Add topOffest to content within Hero Slices

- src/components/ContentHubArticleList/ContentHubArticleList.module.css
> [Update][AES-1346]: add grid support for IE

- src/components/BodyCopy/BodyCopy.js
- src/components/BodyCopy/BodyCopy.stories.mdx
- src/components/Carousel/Carousel.js
- src/components/Heading/Heading.js
- src/components/Heading/Heading.module.css
- src/components/Heading/Heading.stories.mdx
- src/components/MediaWithContent/MediaWithContent.fixture.js
- src/components/MediaWithContent/MediaWithContent.stories.mdx
- src/components/MediaWithContent/components/Content/Content.js
- src/components/MediaWithContent/components/Content/Content.module.css
- src/components/Paragraph/Paragraph.js
- src/components/Paragraph/Paragraph.module.css
- src/components/ProductDetailHeader/components/ProductDetailBody/ProductDetailBody.js
- src/components/SectionHeading/SectionHeading.module.css
- src/components/StoreHoursList/StoreHoursList.js
- src/components/StoreHoursList/__snapshots__/StoreHoursList.spec.js.snap
- src/compositions/StoreDetail/StoreDetail.js
- src/styles/variables/layout.css
This PR makes layout and offeset adjustments to the Hero version on the Media with Content component
https://aesoponline.atlassian.net/browse/AES-1735
> [Feature][AES-1735] Hero offsets

- .storybook/storybook.module.css
- src/components/BodyCopy/BodyCopy.module.css
- src/components/Carousel/Carousel.fixture.js
- src/components/Carousel/Carousel.module.css
- src/components/Carousel/Carousel.stories.mdx
- src/components/Hyperlink/Hyperlink.module.css
- src/components/ImageCarousel/ImageCarousel.fixture.js
- src/components/ImageCarousel/ImageCarousel.js
- src/components/ImageCarousel/ImageCarousel.stories.mdx
- src/components/LinkButtonGroup/LinkButtonGroup.module.css
- src/components/MediaWithContent/MediaWithContent.fixture.js
- src/components/MediaWithContent/MediaWithContent.stories.mdx
- src/components/MediaWithContent/components/Content/Content.module.css
This PR addresses: 
https://aesoponline.atlassian.net/browse/AES-1735 - Navigation and Hero Layout
https://aesoponline.atlassian.net/browse/AES-1751 - Image Carousel Theme
Related to https://github.com/aesop/aesop-web-ui/pull/3089
UAT/UI Testing: https://aes-1744-button-style.acceptance.aesop.com/au/r/candles-landing-test/?contentful=true
> [Feature][AES-1735][AES-1751] Hero Offset and Image Carousel Theme

- src/styles/variables/color.css
This PR updates the HEX value of the copy colour for 
https://aesoponline.atlassian.net/browse/AES-1750
> [Feature][AES-1750] Update copy and heading colour for BodyCopy component

- src/components/ReadMore/ReadMore.module.css
Fix the margin for ReadMore desktop view
> [Update][Feature/AES-1350]: Fix the margin for ReadMore desktop view

- src/styles/variables/color.css
This PR updates the link colour per https://aesoponline.atlassian.net/browse/AES-1750
> [Update][AES-1750] Update BodyCopy Link Colour

- src/components/MediaWithContent/MediaWithContent.stories.mdx
- src/components/SubNav/SubNav.js
- src/components/Video/Video.js
- src/components/Video/Video.module.css
This PR addressed the Button Style inconsistency in https://aesoponline.atlassian.net/browse/AES-1744
-  Add new target prop to sub nav
> [Feature][AES-1744] Hero Button Style

- src/components/ContentHubArticle/ContentHubArticle.module.css
- src/components/ReadMore/ReadMore.js
- src/components/ReadMore/ReadMore.module.css
- src/components/ReadMore/__snapshots__/ReadMore.spec.js.snap
fix the font size and width for ReadMore tablet view
> [Update][AES-1350]: fix the font size and width for ReadMore tablet view

- src/components/AddToCartButton/AddToCartButton.js
- src/components/AddToCartButton/AddToCartButton.spec.js
- src/components/AddToCartButton/AddToCartButton.stories.mdx
- src/components/AddToCartButton/__snapshots__/AddToCartButton.spec.js.snap
- src/components/ProductCommerce/ProductCommerce.js
- src/components/ProductDetailHeader/components/ProductDetailBody/ProductDetailBody.js
- src/components/ProductGridItem/ProductGridItem.js
- src/components/ProductGridItem/__snapshots__/ProductGridItem.spec.js.snap
Address the GEL implementation of https://aesoponline.atlassian.net/browse/AES-1588
> [Feature][AES-1588] Add To Cart Data Test Ref

- src/components/AddToCartButton/AddToCartButton.module.css
- src/components/BodyCopy/BodyCopy.fixture.js
- src/components/BodyCopy/__snapshots__/BodyCopy.spec.js.snap
- src/components/Button/Button.module.css
- src/components/Hyperlink/Hyperlink.js
- src/components/Hyperlink/Hyperlink.module.css
- src/components/LinkButtonGroup/LinkButtonGroup.module.css
- src/components/MediaWithContent/MediaWithContent.stories.mdx
- src/components/StoreDetailHeader/__snapshots__/StoreDetailHeader.spec.js.snap
- src/styles/variables/color.css
This PR addresses the button style updates in Max's comment on https://aesoponline.atlassian.net/browse/AES-1744
https://www.figma.com/file/pXcRya6xAK8hxUGkd22Xpr/Body-Copy-CTA's?node-id=0%3A1
> [Feature][AES-1744] Hyperlink and Button Style Updates

- src/components/Carousel/Carousel.js
- src/components/Carousel/Carousel.utils.js
- src/components/Carousel/__snapshots__/Carousel.spec.js.snap
- src/components/Carousel/components/Pagination/Pagination.js
- src/components/Carousel/components/Pagination/Pagination.module.css
- src/components/Carousel/components/Pagination/Pagination.spec.js
- src/components/Carousel/components/Pagination/__snapshots__/Pagination.spec.js.snap
- src/components/ImageCarousel/__snapshots__/ImageCarousel.spec.js.snap
This PR adds animation to carousel pagination to address https://aesoponline.atlassian.net/browse/AES-1778
> [Feature][AES-1783] Carousel Pagination Animation

- src/components/MediaWithContent/components/Content/Content.module.css
- src/styles/variables/layout.css
This PR addressed the remaining issues in https://aesoponline.atlassian.net/browse/AES-1735, including adding correct margins, removing overrides and updating offset variables.
> [Feature][AES-1735] Hero - correct margins, overrides and offsets

- src/components/AddToCartButton/AddToCartButton.module.css
- src/components/Button/Button.module.css
- src/components/Hyperlink/Hyperlink.module.css
- src/components/LinkButtonGroup/LinkButtonGroup.module.css
- src/components/ProductCommerce/ProductCommerce.js
- src/components/ProductCommerce/ProductCommerce.module.css
- src/components/ProductCommerce/ProductCommerce.stories.mdx
- src/styles/variables/color.css
This PR addresses the height, width and font sizes issues for buttons raised in https://aesoponline.atlassian.net/browse/AES-1744
> [Feature][AES-1744] Add correct button style values

- src/components/Quote/Quote.module.css
This PR address layout and font requirements noted in https://aesoponline.atlassian.net/browse/AES-710
> [Feature][AES-710] Address Quote Component font and layout requirements

- src/components/Carousel/Carousel.module.css
This PR addresses the carousel width of full width images issues noted in https://aesoponline.atlassian.net/browse/AES-907
> [Feature][AES-907] Image Carousel Margins

- src/components/Carousel/Carousel.module.css
This PR addresses the carousel width of full width images issues noted in https://aesoponline.atlassian.net/browse/AES-907
> [Feature][AES-907] Image Carousel Margins Hot-Fix

- src/components/Figure/Figure.js
- src/components/Figure/Figure.module.css
- src/components/Figure/Figure.stories.mdx
- src/components/Image/Image.module.css
This PR adds a offset prop and caption style to address https://aesoponline.atlassian.net/browse/AES-1747 and https://aesoponline.atlassian.net/browse/AES-245
> [Feature][AES-1747] Figure Component add caption styling and offset prop

- src/components/Figure/__snapshots__/Figure.spec.js.snap
This PR adds a offset prop and caption style to address https://aesoponline.atlassian.net/browse/AES-1747 and https://aesoponline.atlassian.net/browse/AES-245 - Updating snapshot
> [Feature][AES-1747] Figure Component - update snapshot

- src/components/MediaWithContent/MediaWithContent.js
- src/components/MediaWithContent/MediaWithContent.module.css
- src/components/MediaWithContent/__snapshots__/MediaWithContent.spec.js.snap
This PR removes the bottom margin from hero slices as requested in https://aesoponline.atlassian.net/browse/AES-1827
> [Feature][AES-1827] Remove bottom margin from hero component

- src/components/SubNav/SubNav.js
- src/components/SubNav/SubNav.module.css
- src/components/SubNav/SubNav.stories.mdx
- src/components/SubNav/__snapshots__/SubNav.spec.js.snap
This PR updates the Sub Nav styles as requested in https://aesoponline.atlassian.net/browse/AES-1664
> [Feature][AES-1664] Sub Nav Styling

- src/components/MediaWithContent/MediaWithContent.fixture.js
- src/components/MediaWithContent/MediaWithContent.js
- src/components/MediaWithContent/MediaWithContent.stories.mdx
- src/components/MediaWithContent/components/Media/Media.js
- src/components/MediaWithContent/components/Media/Media.module.css
This PR adds a `containMedia` prop to address image clipping issues raised in https://aesoponline.atlassian.net/browse/AES-1754
> [Feature][AES-1754] Add containMedia prop to MediaWithContent component

- src/components/DefinitionListWithProductExtract/DefinitionListWithProductExtract.js
- src/components/DefinitionListWithProductExtract/DefinitionListWithProductExtract.spec.js
Added missing data and fixed a proptype for showcase component to resolve warnings.
> [Feature][AES-1511] Create Product Extract Component for How to Use section [Further test fixes to resolve warnings]]

- src/components/ProductDetailHeader/ProductDetailHeader.fixture.js
- src/components/ProductGridItem/ProductGridItem.js
- src/components/ProductGridItem/__snapshots__/ProductGridItem.spec.js.snap
- src/compositions/ProductDetail/ProductDetail.fixture.js
Updating snapshots and test to fix failing ProductGridItemTest
> Fix failing product grid item tests

- .github/workflows/push.yml
- src/components/ProductDetailHeader/ProductDetailHeader.fixture.js
- src/components/ProductGridItem/ProductGridItem.js
- src/components/ProductGridItem/__snapshots__/ProductGridItem.spec.js.snap
- src/compositions/ProductDetail/ProductDetail.fixture.js
This will run the testing & linting actions on all branches, not just master & develop. It will also ignore any tag pushes (e.g releases)
The semantic release command also runs in this workflow however it will not make any changes unless on a 'release' branch (master or develop)
> Run Github Actions on all branches

- src/components/Hyperlink/Hyperlink.module.css
- src/components/LinkButtonGroup/LinkButtonGroup.module.css
- src/components/MediaWithContent/MediaWithContent.fixture.js
This PR adds alignment styles to LinkButtonGroup to address requirements in https://aesoponline.atlassian.net/browse/AES-1744
> [Feature][AES-1744] Add alignment styles to LinkButtonGroup

- src/components/DefinitionListWithProductExtract/DefinitionListWithProductExtract.fixture.js
- src/components/DefinitionListWithProductExtract/__snapshots__/DefinitionListWithProductExtract.spec.js.snap
- src/components/ProductExtract/ProductExtract.fixture.js
- src/components/ProductExtract/ProductExtract.js
- src/components/ProductExtract/ProductExtract.module.css
- src/components/ProductExtract/__snapshots__/ProductExtract.spec.js.snap
Included Flex logic to make image with dynamic while setting max height to 50px as per requirement.
> [Feature][AES-1511] Create Product Extract Component for How to Use section [Add Flex for image]

- src/components/ProductExtract/ProductExtract.module.css
Added logic for image center alignment
> [Feature][AES-1511] Create Product Extract Component for How to Use section [Center align image]

- src/components/HorizontalProductDisplayAccordion/components/AccordionProduct/AccordionProduct.module.css
This PR addresses the animation inconsistencies in https://aesoponline.atlassian.net/browse/AES-1970
> [Feature][AES-49] Candles - Accordion Product Animation

- src/components/FullWidthHeroScroll/FullWidthHeroScroll.js
- src/components/Video/components/VideoPlayer/VideoPlayer.js
- src/components/Video/components/VideoPlayer/VideoPlayer.module.css
This PR adds a prop to the Video component and accompanying styles that will force hide the native play button on iOS if the device is in low power mode. 
https://aesoponline.atlassian.net/browse/AES-2011
> [Feature][AES-2011] Low Power mode fix for Video on iOS

- src/components/ProductExtract/ProductExtract.module.css
Applied final design to thumbnail after decision/discussion with UI/UX team.
- Fixed max-height and max-width of image to 50px an 80px respectively
- Auto width of image to maintain aspect ratio
> [Feature][AES-1511] Image thumbnail CSS adjustments

- src/components/BodyCopy/__snapshots__/BodyCopy.spec.js.snap
- src/components/Carousel/__snapshots__/Carousel.spec.js.snap
- src/components/MediaWithContent/__snapshots__/MediaWithContent.spec.js.snap
- src/components/SectionHeading/SectionHeading.js
- src/components/SectionHeading/SectionHeading.module.css
- src/components/SectionHeading/__snapshots__/SectionHeading.spec.js.snap
This PR addresses: 
- The visual heading ordering issue raised in https://aesoponline.atlassian.net/browse/AES-2030
- The page heading top offset issue https://aesoponline.atlassian.net/browse/AES-1828
> [Feature][AES-2030][AES-1828] Page Heading Style Updates

- src/components/FooterBlock/FooterBlock.css
- src/components/FooterBlock/FooterBlock.js
- src/components/FooterBlock/__snapshots__/FooterBlock.spec.js.snap
- src/compositions/Footer/__snapshots__/Footer.spec.js.snap
Fix the padding of heading in the FooterBlock
> fix: fix heading padding in FooterBlock

- src/components/ProductCommerce/ProductCommerce.module.css
Addresses the flex display issue on iPad https://aesoponline.atlassian.net/browse/AES-2136
> feat: aes-2138 remove flex issue on ipad

- .storybook/GridOverlay.js
- .storybook/GridOverlay.module.css
- src/components/FullWidthHeroScroll/FullWidthHeroScroll.fixture.js
- src/components/FullWidthHeroScroll/FullWidthHeroScroll.js
- src/components/FullWidthHeroScroll/FullWidthHeroScroll.module.css
- src/components/FullWidthHeroScroll/FullWidthHeroScroll.spec.js
- src/components/FullWidthHeroScroll/FullWidthHeroScroll.stories.mdx
- src/components/FullWidthHeroScroll/__snapshots__/FullWidthHeroScroll.spec.js.snap
- src/components/FullWidthHeroScroll/components/BackgroundElement/BackgroundElement.js
- src/components/FullWidthHeroScroll/components/BackgroundElement/BackgroundElement.module.css
- src/components/FullWidthHeroScroll/components/BackgroundElement/index.js
- src/components/MediaWithContent/MediaWithContent.stories.mdx
- src/components/ProductDetailHeader/ProductDetailHeader.stories.mdx
- src/components/TwoColumnLayout/TwoColumnLayout.stories.mdx
- src/compositions/ProductDetail/ProductDetail.stories.mdx
- src/styles/variables/z-index.css
This PR addresses https://aesoponline.atlassian.net/browse/AES-2163 by adding a background element component, styles and logic to display a video or image given props provided
> [Feature][AES-2163] Add Background Image Option to Full Screen Scroll Component

- src/components/Carousel/Carousel.js
Add the ability to pass an array of refs to be assigned to the slides in the carousel.
> feat(carousel): add slideRefs prop

- package-lock.json
- src/components/AddToCartButton/AddToCartButton.js
- src/components/ProductDetailHeader/ProductDetailHeader.fixture.js
- src/components/ProductDetailHeader/ProductDetailHeader.js
- src/components/ProductDetailHeader/components/ProductDetailBody/ProductDetailBody.fixture.js
- src/components/ProductDetailHeader/components/ProductDetailBody/ProductDetailBody.js
- src/components/ProductDetailHeader/components/ProductDetailImage/ProductDetailImage.fixture.js
- src/components/ProductDetailHeader/components/ProductDetailImage/ProductDetailImage.js
- src/components/ProductExtract/ProductExtract.js
- src/components/ProductExtract/__snapshots__/ProductExtract.spec.js.snap
- src/compositions/ProductDetail/ProductDetail.fixture.js
- src/contexts/VariantSelect.context.js
- src/customHooks/useImageTransition.js
This PR makes changes to the PDP Header and Add To Cart components to address https://aesoponline.atlassian.net/browse/AES-2182
- Add is `isSellable` to Add To Cart Components
- Move `cartDisclaimer` to variants level
- Add `size` variants - `singular` and `plural`
- Conditionally add ingredients row if applicable 
- Update image transition hook
> [Feature][AES-2182] PDP - GraphQL service and web-ui GraphQL Schema updates

- src/components/Carousel/components/Slide/Slide.module.css
- src/components/NavigationBar/NavigationBar.module.css
This to address some warnings in web-ui.
> fix: Address Postcss warnings from Web-ui

- src/customHooks/useExecuteOnImpression/useExecuteOnImpression.stories.js
Added 2 knobs to demo the hook's options
> chore: improve useExecuteOnImpression Story

- src/components/HorizontalProductDisplayAccordion/components/AccordionProduct/AccordionProduct.module.css
This PR makes spacing updates to the horizontal product accordion to address https://aesoponline.atlassian.net/browse/AES-2381
Is required by: https://github.com/aesop/aesop-web-ui/pull/3534
> [Feature][AES-2381] Spacing updates for horizontal product accordion 

- package-lock.json
Ran this 5 times and passed all of them for whatever that's worth 🤷‍♂️
> chore: delete node_modules and package-lock and reinstall

- src/components/Hyperlink/Hyperlink.js
- src/components/ProductCommerce/ProductCommerce.js
- src/components/ProductCommerce/ProductCommerce.spec.js
- src/components/ProductGridItem/ProductGridItem.js
- src/components/ProductGridItem/ProductGridItem.spec.js
Added the following:
**clickTrackingFunction**: Initiate click function to push tracking data to google analytics
**trackDataProps**: Included for automation testing scripts 
Related to following Web-UI PR: https://github.com/aesop/aesop-web-ui/pull/3546
> [Feature][AES-2175] Add tracking functionality to ProductCommerce & ProductGridItem Components

- .gitignore
Adding a gitignore file so git doesn't track files irrelevant to this branch.
> chore: add git ignore to GH pages branch

- package-lock.json
- package.json
- setupTests.js
- src/components/Audio/__snapshots__/Audio.spec.js.snap
- src/components/Audio/components/AudioFooter/__snapshots__/AudioFooter.spec.js.snap
- src/components/Carousel/__snapshots__/Carousel.spec.js.snap
- src/components/Carousel/components/NextButton/__snapshots__/NextButton.spec.js.snap
- src/components/Carousel/components/PreviousButton/__snapshots__/PreviousButton.spec.js.snap
- src/components/Checkbox/Checkbox.js
- src/components/DialogBanner/__snapshots__/DialogBanner.spec.js.snap
- src/components/FooterBlock/__snapshots__/FooterBlock.spec.js.snap
- src/components/FullWidthHeroScroll/__snapshots__/FullWidthHeroScroll.spec.js.snap
- src/components/GoogleMap/__snapshots__/GoogleMap.spec.js.snap
- src/components/HorizontalProductDisplayAccordion/__snapshots__/HorizontalProductDisplayAccordion.spec.js.snap
- src/components/HorizontalProductDisplayAccordion/components/AccordionProduct/__snapshots__/AccordionProduct.spec.js.snap
- src/components/Icon/Icon.js
- src/components/Icon/Icon.utils.js
- src/components/Icon/__snapshots__/Icon.spec.js.snap
- src/components/ImageCarousel/__snapshots__/ImageCarousel.spec.js.snap
- src/components/Modal/components/ModalBody/__snapshots__/ModalBody.spec.js.snap
- src/components/NotificationModal/__snapshots__/NotificationModal.spec.js.snap
- src/components/Select/__snapshots__/Select.spec.js.snap
- src/components/StoreDetailHeader/__snapshots__/StoreDetailHeader.spec.js.snap
- src/components/SubNav/__snapshots__/SubNav.spec.js.snap
- src/components/TextInputV2/TextInputV2.js
- src/components/Video/__snapshots__/Video.spec.js.snap
- src/compositions/Footer/__snapshots__/Footer.spec.js.snap
- src/compositions/NewsletterSignUp/__snapshots__/NewsletterSignUp.spec.js.snap
https://github.com/thearnica/react-uid#readme
The uuid package was rendering new ids on every render (bad for a component like Video where the progress causes re-renders), so this has been replaced with React UID.
Snapshots updated to accommodate this.
> Chore: Replace UUID with React UID for persistent IDs

- src/components/FooterBlock/FooterBlock.css
- src/components/FooterBlock/FooterBlock.js
- src/components/FooterBlock/__snapshots__/FooterBlock.spec.js.snap
- src/compositions/Footer/__snapshots__/Footer.spec.js.snap
This PR addresses https://aesoponline.atlassian.net/browse/CON-78 and refactors the heading component with correct heading level
> [Feature][CON-78] Heading Levels in Footer

- package-lock.json
- src/components/HorizontalProductDisplayAccordion/HorizontalProductDisplayAccordion.js
- src/components/HorizontalProductDisplayAccordion/HorizontalProductDisplayAccordion.spec.js
- src/components/HorizontalProductDisplayAccordion/components/AccordionProduct/AccordionProduct.fixture.js
- src/components/HorizontalProductDisplayAccordion/components/AccordionProduct/AccordionProduct.js
- src/components/HorizontalProductDisplayAccordion/components/AccordionProduct/AccordionProduct.spec.js
This PR addresses the tracking requirement in [CON-129](https://aesoponline.atlassian.net/browse/CON-129).
Work on gel involved:-
1. Passing product ref to accordionProduct
2. Enriching with forwardRef function
3. **Introducing new  _callbackWithRef_  function prop** that would allow any external function to have access to the ref of any gel component, generated within the gel components context
4. Improved AccordionProduct.js test coverage to 100% [function testing coverage remains 85% due to default prop. Will address in future PR]
Corresponding **web-ui** PR: https://github.com/aesop/aesop-web-ui/pull/3649
> [Feature/CON-129] add callback function prop to accordionProduct in gel for tracking

- list-js-files.js
- package.json
Not sure if this is worth it. I added it locally to see how many JS files are left and thought I'd raise a PR in case the team sees benefit in it.
> Add npm script to count remaining JS files

- package-lock.json
- src/components/BodyCopy/BodyCopy.module.css
This PR addresses the issue around a tags in body copies where the tag takes the whole line space. Converting it to inline in this context through a CSS change fixes the issue.
https://aesoponline.atlassian.net/browse/CON-136
**Before**
**After**
> [Fix](CON-144): change display to inline for bodycopy a tags

- src/components/ProductDetailHeader/ProductDetailHeader.js
- src/components/ProductDetailHeader/components/ProductDetailBody/ProductDetailBody.js
Removed boilerplate rendering logic to allow rendering to be done in web-ui. 
Change implemented in web-ui ticket: https://github.com/aesop/aesop-web-ui/pull/3739
> [Feature/CON-188]: Refactor out boilerplate logic

- package-lock.json
- src/components/HeroBanner/HeroBanner.types.ts
- src/components/HeroBanner/components/HeroBannerMedia/HeroBannerMedia.tsx
- src/components/HeroBanner/components/HeroBannerMedia/HeroBannerMedia.types.ts
- src/components/SubNav/SubNav.tsx
- src/components/SubNav/SubNav.types.ts
- src/components/SubNav/SubNav.utils.tsx
Relates to https://github.com/aesop/aesop-web-ui/pull/3870 in web-ui
> Feature[CON-124+125]: Hero Banner Fifty Fifty and Full Width Tracking

- .eslintrc
- .prettierrc.js
- .stylelintrc
- package-lock.json
- package.json
This is an awesome milestone 🙌 
Thanks to @maxlew for pushing to publish our public repos on npmjs and @gssumesh for implementing it 😃
> Install aesop-code-styles from npmjs

- src/components/Carousel/__snapshots__/Carousel.spec.tsx.snap
- src/components/Carousel/components/Slide/__snapshots__/Slide.spec.tsx.snap
- src/components/DoubleMedia/__snapshots__/DoubleMedia.spec.tsx.snap
- src/components/Figure/__snapshots__/Figure.spec.tsx.snap
- src/components/FullWidthHeroScroll/__snapshots__/FullWidthHeroScroll.spec.js.snap
- src/components/HeroBanner/__snapshots__/HeroBanner.spec.tsx.snap
- src/components/IconLink/__snapshots__/IconLink.spec.js.snap
- src/components/Image/Image.spec.tsx
- src/components/Image/Image.tsx
- src/components/Image/Image.utils.tsx
- src/components/Image/__snapshots__/Image.spec.tsx.snap
- src/components/ReadMore/__snapshots__/ReadMore.spec.js.snap
- src/components/TextOverFullWidthAsset/__snapshots__/TextOverFullWidthAsset.spec.js.snap
- src/components/Video/__snapshots__/Video.spec.tsx.snap
This PR explicitly sets the `src` of the image tag within the `picture` element. 
Aims to address / aid with addressing https://aesoponline.atlassian.net/browse/CON-513
> [CON-512] Explicity sets the `src` of the image tag within the `picture` element

- src/compositions/DynamicForm/DynamicForm.tsx
- src/compositions/DynamicForm/DynamicForm.types.ts
- src/compositions/DynamicForm/wrappers/Checkbox.tsx
- src/compositions/DynamicForm/wrappers/TextField.tsx
Two main changes:
1. allow setting a form name for a11y
2. set the `name` value on Checkboxes and Texfields
> Dynamic form improvements

- src/components/DoubleMedia/DoubleMedia.tsx
- src/components/DoubleMedia/DoubleMedia.types.ts
Ticket: https://aesoponline.atlassian.net/browse/CON-128
Related web-ui ticket: https://github.com/aesop/aesop-web-ui/pull/3991
> [Feature/CON-128]: add ref for impression tracking

- src/components/Select/Select.tsx
> fix(Select): remove aria-describedby if there is no error

- .eslintrc
- jest.config.js
- package-lock.json
- package.json
Will now print
```
Found 134 test suites
[..................                                                                                                                    ] 18/134 13%  console.error
Warning: Received `false` for a non-boolean attribute `href`.
If you want to write it to the DOM, pass a string instead: href="false" or href={value.toString()}.
If you used to conditionally omit it with href={condition && value}, pass href={condition ? value : undefined} instead.
at a
at /Users/mustafa.mansour/dev/gel/src/components/Hyperlink/Hyperlink.tsx:17:15
at li
at Transition (/Users/mustafa.mansour/dev/gel/node_modules/react-transition-group-npm/cjs/Transition.js:133:30)
at CSSTransition (/Users/mustafa.mansour/dev/gel/node_modules/react-transition-group-npm/cjs/CSSTransition.js:11 …
```
> Testing improvements

- src/components/Select/Select.module.css
- src/components/Select/Select.spec.tsx
- src/components/Select/Select.stories.mdx
- src/components/Select/Select.tsx
- src/components/Select/Select.types.ts
Allow dropdowns to be disabled
> feat(Select): add isEnabled prop

- src/components/DateSelector/DateSelector.module.css
- src/components/DateSelector/DateSelector.spec.tsx
- src/components/DateSelector/DateSelector.stories.mdx
- src/components/DateSelector/DateSelector.tsx
- src/components/DateSelector/DateSelector.types.ts
- src/components/DateSelector/DateSelector.utils.spec.ts
- src/components/DateSelector/DateSelector.utils.ts
- src/components/DateSelector/index.ts
- src/components/index.ts
- src/index.ts
Extracted this [part](https://github.com/aesop/aesop-web-ui/blob/932a4e131df22a28262f4f1eab7d7ad2d0b76ba4/src/app/components-custom/account/information/AccountInfoPersonalForm.js#L145-L169) of Web UI into a component
> Add date selector

- src/components/TextInputV2/TextInputV2.module.css
- src/components/TextInputV2/TextInputV2.tsx
> fix(TextInputV2): add styles when disabled

- src/components/GlobalNavigation/components/DesktopView/components/CloseButton/CloseButton.module.css
- src/components/GlobalNavigation/components/DesktopView/components/CollectionList/CollectionList.module.css
- src/components/GlobalNavigation/components/DesktopView/components/CollectionList/CollectionList.tsx
- src/components/GlobalNavigation/components/TabletView/TabletView.module.css
- src/components/GlobalNavigation/components/TabletView/components/CollectionList/CollectionList.module.css
- src/components/GlobalNavigation/components/TabletView/components/CollectionList/CollectionList.tsx
- src/components/GlobalNavigation/components/TabletView/components/PrimaryMenu/PrimaryMenu.tsx
- src/components/Heading/Heading.tsx
- src/components/Heading/Heading.types.ts
Tackling various accessibility tweaks based on the following document
https://aesoponline.atlassian.net/wiki/spaces/CON/pages/3341058065/MVP+Feedback+Runbook
To identify points tackled, you can match the `scope` of the commit message with the index number of the issue in the document above. E.g. **P-33** refers to **Issue#33**.
> Navigation Accessibility Tweaks

- src/components/GlobalNavigation/components/MobileView/components/ArticleCard/ArticleCard.module.css
- src/components/GlobalNavigation/components/MobileView/components/ArticleList/ArticleList.module.css
Had a stab at solving this issue while trying to write the ticket, scroll snap seems to be pretty well supported.
https://caniuse.com/mdn-css_properties_scroll-snap-type
> Fixing scrolling behaviour for article cards on mobile

- src/components/FullWidthHeroScroll/FullWidthHeroScroll.module.css
- src/components/FullWidthHeroScroll/FullWidthHeroScroll.tsx
- src/components/GlobalNavigation/GlobalNavigation.types.ts
- src/components/GlobalNavigation/components/DesktopView/components/MenuItem/MenuItem.tsx
- src/components/GlobalNavigation/components/DesktopView/components/MenuItem/MenuItem.types.ts
- src/components/GlobalNavigation/components/DesktopView/components/SecondaryMenu/SecondaryMenu.tsx
- src/components/GlobalNavigation/components/MobileView/components/Header/Header.tsx
- src/components/GlobalNavigation/components/TabletView/components/SecondaryMenu/SecondaryMenu.tsx
- src/components/HeroBanner/HeroBanner.module.css
- src/components/HeroBanner/HeroBanner.tsx
- src/components/HeroBanner/HeroBanner.types.ts
- src/components/HeroBanner/components/HeroBannerContent/HeroBannerContent.module.css
- src/components/HeroBanner/components/HeroBannerContent/HeroBannerContent.tsx
- src/components/HeroBanner/components/HeroBannerContent/HeroBannerContent.types.ts
-- Ticket link 
https://aesoponline.atlassian.net/browse/CON-948
--Task
Optimize hero banner padding
Add data-count in cart button
--Solution
use CSS to adjust padding and merge.
> fix(con-948): optimize hero banner padding & add data-count in cart button
