src/components/AddToCartButton/AddToCartButton.stories.mdx, src/contexts/AddToCart.context.js, src/contexts/ProductDetail.context.js, src/contexts/Theme.context.js, src/contexts/VariantSelect.context.js, src/contexts/index.js, src/customHooks/index.js, src/customHooks/useEscapeKeyListener.stories.js, src/customHooks/useHasMounted.stories.js, src/customHooks/useOnScreen.stories.js, src/customHooks/useTheme.js, src/customHooks/useTheme.stories.mdx, src/index.js
This PR adds `ThemeContextProvider` method, `useThemeContext` and `useTheme` hooks to be used to set and consume global values for site theme.
Core Files:
- Theme context story: https://github.com/aesop/aesop-gel/compare/feature/AES-909-theme-colour-context?expand=1#diff-0d1b18038ccf7a61637e9b99d692a5d7
- useTheme Hook: https://github.com/aesop/aesop-gel/compare/feature/AES-909-theme-colour-context?expand=1#diff-09ac27795e0df6ecf0bd2ffdfc1fca26
- ThemeContext: https://github.com/aesop/aesop-gel/compare/feature/AES-909-theme-colour-context?expand=1#diff-cbf32eb1d76799c0b81279ca76bef258
JIRA: https://aesoponline.atlassian.net/browse/AES-909
Usage example: 
```
// ComponentA.js
import { ThemeContextProvider } from '~/contexts';
import { useTheme } from '~/customHooks';
import ComponentB from …
```
=> [Feature][AES-909] Theme Colour Context

src/components/Podium/Podium.js
Found a small typo when generating the podium padding class names.
=> [fix] typo on podium padding rules

src/components/DefinitionList/DefinitionList.js, src/components/DefinitionList/DefinitionList.module.css, src/components/DefinitionList/DefinitionList.stories.mdx
This PR addressed, and removes the filter logic for pairs or terms and descriptions in Definition List to allow non pairs.
> Product Fifty Fifty Slice | Copy Pair not Rendering if 'copy' field is not populated.
https://aesoponline.atlassian.net/browse/AES-1587
=> [Feature][AES-1587] Product Fifty Fifty Slice | Copy Pair not Rendering if 'copy' field is not populated.

src/components/Podium/Podium.module.css, src/components/SectionHeading/SectionHeading.module.css
MediumPaddingBottom was using `padding-top` instead of `padding-top`
=> [Update] issue with Podium Medium Padding Bottom & page title alignment

src/components/BodyCopy/BodyCopy.spec.js, src/components/BodyCopy/__snapshots__/BodyCopy.spec.js.snap, src/components/LinkButtonGroup/LinkButtonGroup.spec.js, src/components/LinkButtonGroup/__snapshots__/LinkButtonGroup.spec.js.snap
Updating tests for PR: https://github.com/aesop/aesop-gel/pull/103
> #### Ticket
> https://aesoponline.atlassian.net/browse/AES-1552
> 
> #### Summary
> Updates to `<BodyCopy />`:
> 
> * Remove content display logic of `cta` `secondaryCta` `linkList`
> * Decided to have display logic handled in web-ui
=> [Feature/AES-155- twocolumn-ctas]: CTAs ins Body Copy

src/components/DefinitionList/DefinitionList.module.css, src/components/ProductGridItem/ProductGridItem.fixture.js, src/components/ProductGridItem/ProductGridItem.js, src/components/ProductGridItem/ProductGridItem.module.css, src/components/ProductGridItem/ProductGridItem.spec.js, src/components/ProductGridItem/ProductGridItem.stories.mdx, src/components/ProductGridItem/ProductGridItemStorybook.module.css, src/components/ProductGridItem/__snapshots__/ProductGridItem.spec.js.snap, src/components/ProductGridItem/index.js, src/components/index.js, src/styles/variables/color.css
[AES-1695](https://aesoponline.atlassian.net/browse/AES-1695)
Product item component that sits on category page of Web-UI
Figma designs: https://www.figma.com/file/nPp9PF2Y29yfBJ2RmNJHYk/Gifting-Experience-2020?node-id=181%3A0
Production site reference: https://www.aesop.com/au/c/skin/cleanse/
- Product image and title are linkable
- On desktop, radio and ATC button are hidden. Hovering over component will display them
- On mobile+tablet, radio and ATC button are displayed.
- If only one variant is available, `info` text is displayed instead of radio
- Keyboard tab focusing on desktop on radio and ATC button will trigger display
**Mobile**
**Tablet**
**Desktop without hover**
**Desktop after hover**
=> [Feature/AES-1695-product-item]: Product Grid Item

src/components/ProductCommerce/ProductCommerce.js, src/components/ProductCommerce/ProductCommerce.spec.js, src/components/ProductCommerce/ProductCommerce.stories.mdx
[AES-1694](https://aesoponline.atlassian.net/browse/AES-1694)
Updating the Product Commerce component to modify the description prop type to accept HTML.
**TODO:**
- Styling will need to be added via web-ui to the component/html passed in
- font size 14px,
- color: `#333`
- link to have medium weight and underline
=> [Feature: AES-1694]: Prod Commerce description type

src/components/ReadMore/ReadMore.module.css
Fix the margin for ReadMore desktop view
=> [Update][Feature/AES-1350]: Fix the margin for ReadMore desktop view

src/components/AddToCartButton/AddToCartButton.fixture.js, src/components/AddToCartButton/AddToCartButton.js, src/components/AddToCartButton/AddToCartButton.stories.mdx, src/components/AddToCartButton/__snapshots__/AddToCartButton.spec.js.snap, src/components/ProductGridItem/ProductGridItem.module.css, src/components/ProductGridItem/__snapshots__/ProductGridItem.spec.js.snap
- Adding styling tweaks to `ProductGridItem`
- Removed 'product name' and 'product context' dependency on `AddToCartButton` component
=> [UPDATE/product-grid]: button + infoHolder style

src/components/DoubleMedia/components/MediaBlock/MediaBlock.module.css
This PR adjusts the bottom margin for the Double Media Block, as requested in https://aesoponline.atlassian.net/browse/AES-708
=> [Feature][AES-708] Adjust margin for Double Media Component

.github/workflows/update-webui.yml
These changes will update the version of Aesop Gel in Aesop Web UI every time a new version (tag) of Gel is published. The update is done on a separate branch and PR is created to merge it to develop.
Very often multiple PR on Aesop Web UI are updating the version of Gel as part of their changes. This can cause conflicts at the time of merge and may require rebasing to drop changes to `package.json` and `package-lock.json`.
1. The workflow runs for every tag push
2. It checks out Aesop Web UI
3. It runs a custom [GitHub action](https://github.com/aesop/aesop-github-action/tree/create-pr-action/create-pr)
[PR 1](https://github.com/aesop/aesop-web-ui/pull/3162): this was created on tag push. Then closed when another tag was pushed.
[PR 2](https://github.com/aesop/aesop-web-ui/pull/3163) …
=> Raise pr on tag push

src/components/ProductCommerce/ProductCommerce.js, src/components/ProductGridItem/ProductGridItem.js
This is a small PR to fix a bug with multiple ProductGridItems or ProductCommerce components on a single page where they would share a `name` attribute and thus only one could properly be 'checked'
=> Use product sku as name for radio groups in ProductCommerce and ProductGridItem

src/components/HorizontalProductDisplayAccordion/HorizontalProductDisplayAccordion.js, src/components/HorizontalProductDisplayAccordion/components/AccordionProduct/AccordionProduct.js
Because of the way this component manages it's `product` state internally we can't update the `products` array after it's been sent to the component. To remedy this I've passed the `AddToCartCopy` as a separate prop that then gets passed into the add to cart button. 
Alternatively this component should have a useEffect that recalculates the `accordionProducts` state each time `props.products` changes.
=> Adding AddToCartCopy to HorizontalProductDisplayAccordion

src/components/HorizontalProductDisplayAccordion/HorizontalProductDisplayAccordion.fixture.js, src/components/HorizontalProductDisplayAccordion/HorizontalProductDisplayAccordion.spec.js
Updating the fixtures to match the new prop types from https://github.com/aesop/aesop-gel/pull/186
=> Horizontal Accordion: update fixtures to fix tests

.huskyrc
PR [183](https://github.com/aesop/aesop-gel/pull/183) eliminates the need for running linting locally on push.
=> chore: remove linting on push

src/components/DoubleMedia/components/MediaBlock/MediaBlock.js
Enabling autoplay as videos were not showing up without it.
=> fix: enable video autoplay

src/components/DefinitionListWithProductExtract/__snapshots__/DefinitionListWithProductExtract.spec.js.snap, src/components/ProductExtract/ProductExtract.js, src/components/ProductExtract/ProductExtract.module.css, src/components/ProductExtract/__snapshots__/ProductExtract.spec.js.snap
Testing different screen sizes showed that the text may sometimes come too close to the image. Thus, set the product description container width to 70% to account for this.
Also updated snapshots.
=> [Feature][AES-1511] Product description box width adjustment

src/components/TextOverFullWidthAsset/TextOverFullWidthAsset.module.css
Currently the image tag has a tiny bit of space after it. This change removes that.
[Stack overflow question about this](https://stackoverflow.com/questions/5804256/image-inside-div-has-extra-space-below-the-image).
=> fix(text over full width asset): fix space after image

src/components/Podium/Podium.js
This PR is a fit to eliminate the fade transition flicker due to incorrect component ordering
=> fix: correct element ordering to eliminate flicker

src/components/MediaWithContent/components/Content/Content.module.css
This PR addresses https://aesoponline.atlassian.net/browse/ECPS-353 by adjusting column css for the media with content component to provide safe zones for background assets.
=> [Feature][ECPS-353] Background Media safe zone CSS for MediaWithContent

package-lock.json, package.json, src/components/FlyinPanel/FlyinPanel.js, src/components/FlyinPanel/FlyinPanel.spec.js, src/components/Icon/Icon.js, src/components/Icon/Icon.spec.js
From version 5 [Webpack will no longer automatically add browser polyfills for core node modules](https://webpack.js.org/blog/2020-10-10-webpack-5-release/#automatic-nodejs-polyfills-removed). 
The current version of uuid used in Gel relied on those polyfills from web ui. This is also reflected in the output of the build command.
Update uuid package to the latest version which can run on node/browser without relying on external polyfills. This is in preparation for Web UI updating Webpack version. The output of the build command after the version update no longer shows the warning seen above.
I updated locations where the library was used and checked that it still works.
=> chore(deps): update uuid to latest version

.github/workflows/update-webui.yml
Set env variable using the new specified way [here](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable)
I tried this with a test tag and you can see the logs [here](https://github.com/aesop/aesop-gel/runs/1439647915?check_suite_focus=true). I cancelled the job before it raised a PR on web ui.
=> chore: remove deprecated set-env call

src/customHooks/useOnScreen.js
The `isBrowser` check was only included for the first condition, this change makes it before all conditions.
=> fix: incorrect window check

src/components/MediaWithContent/MediaWithContent.js, src/components/MediaWithContent/components/Content/Content.js
To help address https://aesoponline.atlassian.net/browse/AES-2257 this PR adds a `hasSerifFontHeading` prop to the MediaWithContent component
=> [Feature][AES-2257] `hasSerifFontHeading` prop for MediaWithContent component

src/components/Carousel/Carousel.js, src/components/Carousel/components/CarouselIntroduction/CarouselIntroduction.js
Most of the time the slide description is just a `string`, however, sometimes it's a react node. This change allows the component to accept both
=> fix: update carousel prop types

scripts/componentBoilerplate/assets/index.js
Because the components are now exported as named exports, the existing import statement breaks.
=> chore(compboilerplate): fix import statement

src/components/Checkbox/Checkbox.js, src/components/Checkbox/__snapshots__/Checkbox.spec.js.snap, src/components/Select/Select.module.css, src/components/TextInputV2/TextInputV2.module.css, src/compositions/Footer/__snapshots__/Footer.spec.js.snap, src/compositions/NewsletterSignUp/__snapshots__/NewsletterSignUp.spec.js.snap
This PR makes some small changes to form components to pave the way for them to be used together. The changes are:
* Checkbox: wrap in `div` instead of `Fragment` to ensure the error message is always displayed under the label and never next to it
* Select:  reduce the font size on smaller viewports
* InputTextV2: change styles (transition duration, line height) to match Select
=> Improve form element styles

.github/workflows/push.yml, package.json
This stops running `build:dev` for release as `build:prod` runs after it anyway
=> Improve GH action

.github/workflows/push.yml
This is another attempt to address the intermittent issue we get on GH where it fails to run `npm ci`.
I noticed that currently (on `develop`) the node version used in GH is 14.x. However, Gel uses `10.16.0`. This PR specifies version 10.18.0 to be used (a note on that later). I ran the GH action for this commit 4 times and it passed every time, hopefully this does it 🤞 
Note: originally I tried using node v 10.16.0 to match what's used by Gel, however, `semantic-release` requires version 10.18.0 or higher.  That's why I went with 10.18.0.
=> Specify node version in GH action

jest.config.js
This adds the 'text-summary' test coverage reported. The reporter just prints to the console the overall coverage percentages. It can be seen [here](https://github.com/aesop/aesop-gel/pull/306/checks?check_run_id=1803094628#step:6:352) in the build logs for this commit.
=> chore: add text-summary to the reporters

.github/workflows/deploy-gh-pages.yml
This PR creates a GH workflow that will run every time a git version tag is pushed. It will update the Storybook preview deployed at https://aesop.github.io/aesop-gel/.
Test run:
* logs: https://github.com/aesop/aesop-gel/actions/runs/546945704
* commit pushed to gh-pages branch: https://github.com/aesop/aesop-gel/commit/e173e448060a9b5db5fed90456ec86bad50069f4
*Note*: this [workflow](https://github.com/aesop/aesop-gel/pull/312/checks?check_run_id=1852136884) failed because I deleted the tag before it check it out. And I cancelled this [workflow](https://github.com/aesop/aesop-gel/pull/312/checks?check_run_id=1852128677) as it's not needed.
=> Automate GH Pages deployment

.github/workflows/deploy-gh-pages.yml
GH workflows [can be triggered manually](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch). 
This PR adds the ability to trigger deployment to GH Pages manually. The UI will look like this
=> Allow running deployment manually

package.json
As per title, the PR replaces `uuid` with `react-uid` in peer dependencies
=> [Chore] Replace uuid with react-uid in peer dependencies

src/compositions/DynamicForm/DynamicForm.js, src/compositions/DynamicForm/wrappers/Checkbox.js, src/compositions/DynamicForm/wrappers/Select.js, src/compositions/DynamicForm/wrappers/TextField.js, src/index.js
This PR aims to address IE11 legacy issue by implementing the developer suggested code in https://react-hook-form.com/faqs#BrowserSupport, which is to use the IE hook. 
Web UI Branch using these changes can be found [here](https://github.com/aesop/aesop-web-ui/compare/feature/demo-IE-dynamicForm) and is deployed [here](https://demo-ie-dynamicform.acceptance.aesop.com/au).
Screenshot
=> [Update] Use the IE fallback hook for React Hook Form

src/utils/environment/environment.js
These changes eliminate the need to check that the code is executing in the browser before checking for the browser type.
=> feat: wrap browser detection variables in window detection

rollup.config.js, src/components/Audio/Audio.customHooks.js, src/contexts/GoogleMapsContext/GoogleMapsStore.js
Previously, dynamic (lazy) loading of modules was not working on Aesop Web UI, so it was necessary to instruct webpack to load them at the start. However, now it is working so there is no need to do this. This change should also reduce our initial bundle size especially that these components are seldom used.
Happy to demo dynamic module loading if anyone wants to see it in action.
=> feat: lazy load external npm modules

src/components/FlyinPanel/FlyinPanel.js, src/components/Modal/Modal.js
Access to the `document` without a check is causing errors when Gel is used outside the browser (i.e. NextJS). This change wraps them in a check to prevent execution unless in the browser.
=> fix: wrap document access in window check

rollup.config.js
This is to address these [errors](https://github.com/aesop/aesop-gel/runs/2081261145?check_suite_focus=true#step:7:17) during the build.
=> Exclude scripts folder from TS compile

src/components/Accordion/Accordion.tsx, src/components/Accordion/Accordion.types.tsx, src/components/Figure/Figure.tsx, src/components/Figure/Figure.types.ts, src/components/Heading/Heading.tsx, src/components/Heading/Heading.types.ts, src/components/Image/Image.tsx, src/components/Image/Image.types.ts, src/components/Paragraph/Paragraph.tsx, src/contexts/AddToCartContext/AddToCartContext.tsx, src/contexts/AddToCartContext/AddToCartContext.types.ts, src/contexts/GoogleMapsContext/GoogleMapsContext.tsx, src/contexts/GoogleMapsContext/GoogleMapsContext.types.ts, src/contexts/LoadMoreContext/LoadMoreContext.tsx, src/contexts/LoadMoreContext/LoadMoreContext.types.ts, src/contexts/NavBarThemeContext/NavBarThemeContext.tsx, src/contexts/NavBarThemeContext/NavBarThemeContext.types.ts, src/contexts/ProductDetailContext/ProductDetailContext.tsx, src/contexts/ProductDetailContext/ProductDetailContext.types.ts, src/contexts/ThemeContext/ThemeContext.tsx, src/contexts/ThemeContext/ThemeContext.types.ts, src/contexts/VariantSelectContext/VariantSelectContext.tsx, src/contexts/VariantSelectContext/VariantSelectContext.types.ts
This PR refactors existing TS code to:
1. Prefix `props` with the name of the component/context they're for
2. Move css imports to the last line of imports in the file
Closes #341
=> Rrefactor to new conventions

src/components/GoogleMap/GoogleMap.js
Currently, one of the dependencies of the `renderToString` method is the Node Stream module. This isn't an issue at the moment as Webpack v4 (and older) provide a polyfill for it. However, from v5 onwards we'd need to provide our own polyfill for it.
Fortunately, there is a browser friendly alternative provided in the React Dom library. Switching to it remove the `Stream` dependency from the build files as seen in the diff below. In addition to moving to the browser version, I've switched to using `renderToStaticMarkup`. This method is sufficient for our use case as we won't be hydrating the component later and thus don't need `renderToString`.
I deployed a Web UI branch using this Gel branch [here](https://demo-react-dom-change.acceptance.aesop.com/au). It works in IE too @kevin-ho87 …
=> Fix React Dom Server dependency in browser

.github/workflows/push.yml
I re-ran this more than 5 times and it passed. Hoping it fixes our build issues 🤞
=> ci: using checkout v1 and npm cache to avoid weird build issues

src/components/Quote/Quote.tsx
I noticed this error in Web UI
The stack trace led me to this which looked like the Quote component
=> fix(quote): capture and use the ref argument

src/components/ProductDetailHeader/ProductDetailHeader.js, src/components/ProductDetailHeader/components/ProductDetailBody/ProductDetailBody.js
**Ticket**
https://aesoponline.atlassian.net/browse/CON-188
Added both flyout paragraphs as props through the updated copy to be rendered in the ProductDetailBody.js component.
**Screenshots**
Before [No Paragraphs]
After [Both Boilerplate Paragraphs]
=> [Feature/CON-188]: add ingredient flyouts 1 and 2 

.github/workflows/tag-push.yml
As the `develop` branch is no longer being used and will be deleted soon I thought we should disable this part of the workflow until we figure out how to update Gel on Web UI.
=> chore: disable update_web_ui workflow

.github/workflows/push.yml
This is to upload our coverage reports to CC Quality.
The successful build has uploaded the report as seen below at this [url](https://codeclimate.com/repos/6082153d47d59401b600bf71/settings/test_reporter)
=> Integrate test reporter from Quality

.github/workflows/push.yml
GH doesn't expose the branch name and commit hash as env vars so it needs to be done manually.
=> Set value for commit hash and branch name for CC Quality

dist/components/SectionHeading/index.d.ts, dist/index.d.ts, src/components/SectionHeading/SectionHeading.types.ts
This PR updates the `subHeading` prop in the `SectionHeading` component to meet the requirements of https://github.com/aesop/aesop-web-ui/blob/develop/src/app/components-custom/contentful/Slices/PageTitle/PageTitle.js#L16
=> Update `SectionHeading` type API

dist/index.d.ts, src/types/index.ts
The PR simply ensures the type `OnAddToCartClick` is exposed / exported
=> Export `OnAddToCartClick` type

src/types/Component.types.ts, src/types/index.ts
Moving away from `React.FC` (refer to discussion [here](https://github.com/aesop/aesop-gel/pull/397#discussion_r614417432)) we thought it would be handy to create our types instead of manually needing to specify the return type for components (which would almost always be the same).
I created 2 new types: `ComponentWithChildren` and `ComponentWithoutChildren` and migrated Transition to use `ComponentWithChildren` to demo it.
Any feedback is appreciated 😃
=> Typescript: add shared component types

src/components/Button/Button.tsx
I was trying to assign `aria-expanded` to Button and found that nothing was happening. This change allows passing additional props to Button which will then be passed to the underlying <button>.
=> feat: pass other props to button html

src/components/TextInputV2/TextInputV2.types.ts, src/compositions/DynamicForm/DynamicForm.fixture.ts, src/compositions/DynamicForm/DynamicForm.spec.tsx, src/compositions/DynamicForm/DynamicForm.stories.mdx, src/compositions/DynamicForm/DynamicForm.tsx, src/compositions/DynamicForm/DynamicForm.types.ts, src/compositions/DynamicForm/validators/validators.spec.ts, src/compositions/DynamicForm/validators/validators.ts, src/compositions/DynamicForm/validators/validators.types.ts
- fix `onChange` TS type on InputTextV2
- Improvements to DynamicForm
- Add validation rule to check 1 field equals another
- Allow specifying validation behaviour (onChange, onSubmit, etc)
- Fix onSubmit TS type
=> Form field enhancements

src/components/PersonalInfoSummary/PersonalInfoSummary.fixture.ts, src/components/PersonalInfoSummary/PersonalInfoSummary.module.css, src/components/PersonalInfoSummary/PersonalInfoSummary.spec.tsx, src/components/PersonalInfoSummary/PersonalInfoSummary.stories.mdx, src/components/PersonalInfoSummary/PersonalInfoSummary.tsx, src/components/PersonalInfoSummary/PersonalInfoSummary.types.ts, src/components/PersonalInfoSummary/index.ts, src/components/PersonalInfoSummary/utils/utils.spec.ts, src/components/PersonalInfoSummary/utils/utils.ts, src/components/index.ts, src/index.ts
The purpose is to move out [this](https://github.com/aesop/aesop-web-ui/blob/develop/src/app/components-custom/account/information/AccountInfoPersonal.js#L49-L80) component so it can be used in aesop-com.
=> Create personal account info summary comp

src/components/TextInputV2/TextInputV2.tsx
@mishmaccas's [automated a11y tests](https://aesoponline.atlassian.net/browse/ENG-138?focusedCommentId=165229) have picked up a violation that the field's `aria-describedby` references an element not present in the DOM. This change places the `aria-describedby` attribute only if there is an error in which case the error message will be in the DOM.
=> Add aria-describedby if there is an error

src/components/Audio/__snapshots__/Audio.spec.tsx.snap, src/components/BynderWidget/__snapshots__/BynderWidget.spec.tsx.snap, src/components/GoogleMap/__snapshots__/GoogleMap.spec.js.snap, src/components/Hyperlink/Hyperlink.stories.mdx, src/components/Hyperlink/Hyperlink.tsx, src/components/Hyperlink/Hyperlink.types.ts, src/components/Loading/Loading.module.css, src/components/Loading/Loading.stories.mdx, src/components/Loading/Loading.tsx, src/components/Loading/Loading.types.ts, src/components/Loading/__snapshots__/Loading.spec.tsx.snap
1. **HyperLink**: deprecate the `style` prop because it violates an eslint [rule](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/style-prop-object.md) requiring consuming code to disable it. Add a new prop to offer the same functionality.
2. **Loading**: add `align` prop to allow position the loading dots
=> Component enhancements

src/compositions/DynamicForm/DynamicForm.types.ts, src/compositions/DynamicForm/index.ts
Exporting the schema type to help consumers get type validation instead of using `any`.
=> fix(DynamicForm): export schema type

src/components/GlobalNavigation/components/DesktopView/components/CollectionImage/CollectionImage.tsx, src/components/GlobalNavigation/components/DesktopView/components/CollectionImage/CollectionImage.types.ts, src/components/GlobalNavigation/components/DesktopView/components/CollectionLayout/CollectionLayout.tsx, src/components/GlobalNavigation/components/DesktopView/components/CollectionList/CollectionList.tsx, src/components/GlobalNavigation/components/DesktopView/components/CollectionList/CollectionList.types.ts, src/components/GlobalNavigation/components/PromotionCard/PromotionCard.tsx, src/components/GlobalNavigation/components/PromotionCard/PromotionCard.types.ts
As per QA requirements, added data-test-refs for highlighted regions in new Nav for Desktop view.
https://lucid.app/lucidchart/invitations/accept/inv_9be02fa5-a747-4e4d-a0a1-95f90395dc32
**Changes Video**
https://user-images.githubusercontent.com/42990483/133234043-646f46f5-daad-4f14-bda6-e9d756fe27e2.mov
**Identifiers used**
TLC => Top Level Collection
NECO => Nested Collection
NONECO => Notable Nested Collection
TOD => Taxonomy Of Design
With **Read**, I chose to identify the second ul, i.e. the **Read-Collection**, by adding the suffix "-READ" ahead of the TLC naming. This is to accomodate the implementation in code, where its seen that a second ul only comes in the first column of the nav panel if it is a **Read-Collection** (Screenshot below for reference).
Keen to get feedback. …
=> [Feature/Nav]: Add dataTestRefs for desktop view

src/compositions/DynamicForm/DynamicForm.tsx, src/compositions/DynamicForm/DynamicForm.types.ts, src/compositions/DynamicForm/FormField.tsx, src/compositions/DynamicForm/index.ts
The main changes in this PR are:
- using [discriminated union type](https://basarat.gitbook.io/typescript/type-system/discriminated-unions#discriminated-union) to make the schema definition more robust and remove unnecessary optional modifier on properties
- moving some of the jsx out to a new component to keep files short and clear
- renaming some loop variables for clarity
=> refactor(DynamicForm): improve TS defintion

.eslintrc
This is to disable the maximum lines per function rule in test files as the callback functions passed to `describe` and `it` will easily violate this.
=> chore(eslint): disable max lines/func in spec files

src/components/DateSelector/DateSelector.module.css, src/components/DateSelector/DateSelector.spec.tsx, src/components/DateSelector/DateSelector.stories.mdx, src/components/DateSelector/DateSelector.tsx, src/components/DateSelector/DateSelector.types.ts, src/components/DateSelector/DateSelector.utils.ts
Changes:
- Allow the component to be disabled by adding the `isEnabled` prop
- Make the component take 100% width of the element its in
- Fix an issue where onChange was called twice when the currently selected day value was higher than the number of days in the current month
=> Date selector fixes

src/components/GlobalNavigation/components/TabletView/components/CollectionItem/CollectionItem.tsx, src/components/Hyperlink/Hyperlink.tsx, src/components/Hyperlink/Hyperlink.types.ts
Adds the ability pass both a data-test-ref and a data-test-id to the Hyperlink component. 
This improves automation testing as we can specify items in lists more accurately.
=> [Hyperlink] adding option to add data-test-id to Hyperlinks

src/components/DateSelector/index.ts, src/components/Select/index.ts
This is to avoid having to re-declare those types in consuming code bases.
=> feat: export common Prop types for consumers

src/components/GlobalNavigation/GlobalNavigation.hooks.ts, src/components/GlobalNavigation/GlobalNavigation.types.ts, src/components/GlobalNavigation/components/MobileView/MobileView.tsx, src/customHooks/index.ts
-- Add 'isOpenSearchBackToMenu' in GlobalNavigation
-- Web-Ui will pass 'isOpenSearchBackToMenu' to 'MobileView.tsx' after clicking back button
-- 'isOpenSearchBackToMenu' is a boolean to control open Menu or not when travelling back from Search and Stores
=> [Feature/CON-845 Add back button]

src/components/GlobalNavigation/components/TabletView/components/PrimaryMenu/PrimaryMenu.module.css, src/components/GlobalNavigation/components/TabletView/components/PrimaryMenu/PrimaryMenu.tsx
Ticket link:
https://aesoponline.atlassian.net/browse/CON-961
Issue:
Navigation renders search icon near-invisible on tablet in light theme.
=> fix(con-961): fix search icon color in light theme

src/components/GlobalNavigation/components/DesktopView/components/CollectionList/CollectionList.module.css, src/styles/variables/font.css
Short term solution:
Change font-weight from 400 to 500 for all region.
=> fix(con-957): fix category heading not bold on some asian site

src/components/DoubleMedia/components/MediaBlock/MediaBlock.tsx, src/components/Video/Video.module.css, src/components/Video/Video.tsx, src/components/Video/Video.types.ts
Ticket link:
https://aesoponline.atlassian.net/browse/CON-943
Solution:
Remove padding-top of video in media block.
Before:
After:
=> fix(CON-943): fix video height in media block
